#:schema https://mise.jdx.dev/schema/mise-task.json

["brew:bundle"]
description = "Install Homebrew packages from Brewfile"
dir = "{{env.DOTFILES}}"
run = [
	"brew bundle --file stow/Brewfile",
	"brew bundle cleanup --file stow/Brewfile",
]

["brew:cleanup"]
description = "Uninstall Homebrew packages removed from Brewfile"
dir = "{{env.DOTFILES}}"
run = "brew bundle cleanup --force --file stow/Brewfile"

["dotfiles:clean"]
description = "Delete stowed dotfiles"
dir = "{{env.DOTFILES}}"
run = "stow --verbose --delete --target ~ stow"

["dotfiles:install"]
description = "Install stowed dotfiles"
dir = "{{env.DOTFILES}}"
run = [
	"git submodule sync --quiet",
	"git submodule update --init",
	"stow --verbose --restow --target ~ stow",
]

["dotfiles:update"]
description = "Update stowed dotfiles"
dir = "{{env.DOTFILES}}"
run = [
	"brew update",
	"brew upgrade",
	"zprezto-update",
	"git submodule sync",
	"git submodule update",
]
