packages:
  - tools/*
overrides:
  "@types/node": 24.13.3
allowBuilds:
  "@google/genai": true
  "@mongodb-js/zstd": false
  "@parcel/watcher": false
  esbuild: true
  msgpackr-extract: false
  node-liblzma: false
  protobufjs: true
