tap 'mongodb/brew'
tap 'stripe/stripe-cli'

brew 'cloudflared'
brew 'cosign'
brew 'docker'
brew 'gh'
brew 'git'
brew 'glab'
brew 'jj'
brew 'mas'
brew 'mise'
brew 'mprocs'
brew 'stow'
brew 'stripe/stripe-cli/stripe'
brew 'terminal-notifier'
brew 'watchman'
brew 'xorriso'
brew 'yazi'
brew 'zsh'

cask '1password-cli'
cask '1password'
cask 'atuin-desktop'
cask 'bruno'
cask 'copilot-cli'
cask 'cyberduck'
cask 'dbeaver-community'
cask 'firefox@developer-edition'
cask 'flux-app'
cask 'font-fira-code-nerd-font'
cask 'ghostty'
cask 'github'
cask 'gpg-suite-no-mail'
cask 'headlamp'
cask 'keybase'
cask 'macpass'
cask 'notion'
cask 'podman-desktop'
cask 'todoist-app'
cask 'utm'
cask 'visual-studio-code'
cask 'zed'

mas "Boop", id: 1518425043
mas "CrystalFetch", id: 6454431289
mas "DaisyDisk", id: 411643860
mas "HazeOver", id: 430798174
mas "Magnet", id: 441258766
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
