tap 'github/gh'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'stripe/stripe-cli'

brew 'awscli'
brew 'git'
brew 'gh'
brew 'kubectl'
brew 'mas'
brew 'ngrep'
brew 'ripgrep'
brew 'stow'
brew 'stripe/stripe-cli/stripe'
brew 'terminal-notifier'
brew 'watchman'
brew 'zsh'

cask 'babeledit'
cask 'cyberduck'
cask 'dbeaver-community'
cask 'flux'
cask 'font-fira-code'
cask 'gas-mask'
cask 'gpg-suite-no-mail'
cask 'graphiql'
cask 'iterm2'
cask 'kap'
cask 'keybase'
cask 'macpass'
cask 'skype'
cask 'sourcetree'

mas "Boop", id: 1518425043
mas "DaisyDisk", id: 411643860
mas "HazeOver", id: 430798174
mas "Magnet", id: 441258766
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
