---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  install:
    cmds:
      - asdf plugin add awscli https://github.com/MetricMike/asdf-awscli.git
      - asdf plugin add bun https://github.com/cometkim/asdf-bun.git
      - asdf plugin add deno https://github.com/asdf-community/asdf-deno.git
      - asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git
      - asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
      - asdf plugin add kubectl https://github.com/asdf-community/asdf-kubectl.git
      - asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      - asdf plugin add packer https://github.com/asdf-community/asdf-hashicorp.git
      - asdf plugin add pnpm https://github.com/jonathanmorley/asdf-pnpm.git
      - asdf plugin add python https://github.com/danhper/asdf-python.git
      - asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
      - asdf plugin add rust https://github.com/code-lever/asdf-rust.git
      - asdf plugin add terraform https://github.com/asdf-community/asdf-hashicorp.git

  update:
    cmds:
      - brew update
      - brew upgrade asdf
      - asdf plugin update --all
