#!/bin/bash

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

mkdir -p iterm/themes
curl -L https://raw.githubusercontent.com/dracula/iterm/master/Dracula.itermcolors \
  > iterm/themes/Dracula.itermcolors

# Install the Solarized Dark theme for iTerm
open "iterm/themes/Dracula.itermcolors"

# Don’t display the annoying prompt when quitting iTerm
defaults write com.googlecode.iterm2 PromptOnQuit -bool false
