#!/bin/sh
mkdir -p zsh/bundle
curl -L git.io/antigen \
  >  zsh/bundle/antigen.zsh

git clone https://github.com/chriskempson/base16-shell.git \
  ~/.config/base16-shell

git clone https://github.com/dracula/zsh.git \
  ~/.config/dracula
