[env]
DOTFILES = { required = true }
EDITOR = "code"
MISE_ENV_FILE = ".env"
HOLODECK_SSL_CERT_PATH = "/Users/jonno/holodeck-localhost.pem"
HOLODECK_SSL_KEY_PATH = "/Users/jonno/holodeck-localhost-key.pem"
TODOIST_API_TOKEN = "{{ exec(command='op read \"op://Private/Todoist API token/password\"', cache_duration='8h') }}"

[settings]
trusted_config_paths = ["~/src/btp", "~/src/work"]

[tools]
"npm:corepack" = "latest"
"npm:@typespec/compiler" = "latest"
age = "latest"
bun = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
cloudflared = "latest"
cosign = "latest"
deno = "2"
flux2 = "latest"
go = "latest"
helm = "latest"
jq = "latest"
kubectl = "latest"
node = "24"
opentofu = "latest"
packer = "latest"
python = "latest"
slsa-verifier = "latest"
sops = "latest"
talosctl = "latest"
uv = "latest"

[task_config]
includes = [".config/mise/tasks/dotfiles.toml"]
