[bootstrap.macos.keyboard]
key_repeat = 2
initial_key_repeat = 15

[bootstrap.macos.finder]
show_pathbar = true

[bootstrap.macos.defaults]
"com.apple.Finder" = { AppleShowAllFiles = true }

[tools]
"npm:@typespec/compiler" = "1.13.0"
"npm:corepack" = "0.35.0"
"npm:typescript-language-server" = "5.3.0"
"npm:typescript" = "7.0.2"
age = "1.3.1"
atuin = "18.17.1"
aube = "1.28.0"
fnox = "1.31.0"
gh = "2.96.0"
go = "1.26.5"
helm = "4.2.3"
hk = "1.51.0"
jq = "1.8.2"
lima = "2.1.4"
node = "24"
podman = "6.0.1"
python = "3.14.6"
ripgrep = "15.2.0"
shellcheck = "0.11.0"
sops = "3.13.2"
starship = "1.26.0"
usage = "3.5.5"
uv = "0.11.29"
workmux = "0.1.224"
yq = "4.53.3"
zellij = "0.44.3"

[task_config]
includes = [".config/mise/tasks/dotfiles.toml"]
