[env]
_.file = "~/.config/mise/.env"
DOTFILES = { required = true }
EDITOR = "code"

[settings]
dotfiles.root = "~/src/btp/dotfiles"
env_shell_expand = true
node.corepack = true
node.npm_shim = false

[bootstrap.repos]
"~/.config/zsh/.zprezto" = { url = "https://github.com/sorin-ionescu/prezto.git", ref = "master" }
"~/.config/ghostty/themes" = { url = "https://github.com/dracula/ghostty.git", ref = "main" }
"~/.config/opencode/themes" = { url = "https://github.com/dracula/opencode.git", ref = "main" }
"~/.config/base16-shell" = { url = "https://github.com/chriskempson/base16-shell.git", ref = "master" }
"~/src/btp/dotfiles/.zprezto-contrib/zsh-notify" = { url = "https://github.com/marzocchi/zsh-notify.git", ref = "master" }

[bootstrap.hooks.post-repos]
run = "git -C ~/.config/zsh/.zprezto submodule update --init --recursive"

[bootstrap.user]
login_shell = "/bin/zsh"

[bootstrap.packages]
"brew:git" = "latest"
"brew:jj" = "latest"
"brew:mas" = "latest"
"brew:mprocs" = "latest"
"brew:terminal-notifier" = "latest"
"brew:watchman" = "latest"
"brew:xorriso" = "latest"
"brew:yazi" = "latest"
"brew:zsh" = "latest"

"brew-cask:1password-cli" = "latest"
"brew-cask:1password" = "latest"
"brew-cask:atuin-desktop" = "latest"
"brew-cask:bruno" = "latest"
# "brew-cask:cyberduck" = "latest"
"brew-cask:dbeaver-community" = "latest"
"brew-cask:firefox@developer-edition" = "latest"
"brew-cask:flux-app" = "latest"
"brew-cask:font-fira-code-nerd-font" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:github" = "latest"
# "brew-cask:gpg-suite-no-mail" = "latest"
# "brew-cask:keybase" = "latest"
"brew-cask:macpass" = "latest"
"brew-cask:podman-desktop" = "latest"
"brew-cask:todoist-app" = "latest"
"brew-cask:visual-studio-code" = "latest"

"mas:1518425043" = "latest" # Boop
"mas:6454431289" = "latest" # CrystalFetch
"mas:411643860" = "latest" # DaisyDisk
"mas:430798174" = "latest" # HazeOver
"mas:441258766" = "latest" # Magnet
"mas:425424353" = "latest" # The Unarchiver
"mas:497799835" = "latest" # Xcode

[bootstrap.brew.taps]
"showpad/gitlab" = "git@gitlab.com:showpad-code/devops/homebrew.git"


[dotfiles]
"~/AGENTS.md" = { source = "~/src/btp/dotfiles/home/AGENTS.md", mode = "symlink" }
"~/CLAUDE.md" = { mode = "symlink" }
"~/.agents/skills" = { mode = "symlink" }
"~/.claude" = { mode = "symlink-each" }
"~/.claude/skills" = { source = "~/src/btp/dotfiles/.agents/skills", mode = "symlink" }
"~/.config/1Password" = { mode = "symlink" }
"~/.config/atuin/config.toml" = { mode = "symlink" }
"~/.config/fnox/config.toml" = { mode = "copy" }
"~/.config/gh" = { mode = "symlink" }
"~/.config/ghostty/config" = { mode = "symlink" }
"~/.config/git/btp.gitconfig" = { mode = "symlink" }
"~/.config/git/config" = { mode = "template" }
"~/.config/git/ignore" = { mode = "copy" }
"~/.config/git/work.gitconfig" = { mode = "symlink" }
"~/.config/gpg/gpg-agent.conf" = { mode = "symlink" }
"~/.config/gpg/gpg.conf" = { mode = "symlink" }
"~/.config/homebrew/Brewfile" = { mode = "symlink" }
"~/.config/jj/config.toml" = { mode = "symlink" }
"~/.config/kube/config" = { mode = "symlink" }
"~/.config/mise" = { mode = "symlink-each"}
"~/.config/opencode" = { mode = "symlink-each" }
"~/.config/starship/starship.toml" = { mode = "symlink" }
"~/.config/workmux/config.yaml" = { mode = "symlink" }
"~/.config/zellij" = { mode = "symlink" }
"~/.config/zsh" = { mode = "symlink-each" }
"~/.zprezto-contrib" = { mode = "symlink" }
"~/.zshenv" = { mode = "symlink" }
