[env]
_.file = "~/.config/mise/.env"
DOTFILES = { required = true }
EDITOR = "code"
HOMEBREW_BUNDLE_FILE = { default = "{{ env.HOME }}/src/btp/dotfiles/Brewfile" }

[settings]
dotfiles.root = "~/src/btp/dotfiles"
env_shell_expand = true
node.corepack = true
node.npm_shim = false

[bootstrap.repos]
"~/.config/zsh/.zprezto" = { url = "https://github.com/sorin-ionescu/prezto.git", ref = "master" }
"~/.config/ghostty/themes" = { url = "https://github.com/dracula/ghostty.git", ref = "main" }
"~/.config/opencode/themes" = { url = "https://github.com/dracula/opencode.git", ref = "main" }
"~/.config/base16-shell" = { url = "https://github.com/chriskempson/base16-shell.git", ref = "master" }
"~/src/btp/dotfiles/.zprezto-contrib/zsh-notify" = { url = "https://github.com/marzocchi/zsh-notify.git", ref = "master" }

[bootstrap.hooks.post-repos]
run = "git -C ~/.config/zsh/.zprezto submodule update --init --recursive"

[bootstrap.user]
login_shell = "/bin/zsh"

[dotfiles]
"~/.agents/skills" = { mode = "symlink" }
"~/.claude/skills" = "~/src/btp/dotfiles/.agents/skills"
"~/.config/1Password" = { mode = "symlink" }
"~/.config/atuin/config.toml" = { mode = "symlink" }
"~/.config/fnox/config.toml" = { mode = "copy" }
"~/.config/gh" = { mode = "symlink" }
"~/.config/ghostty/config" = { mode = "symlink" }
"~/.config/git" = { mode = "symlink-each" }
"~/.config/git/ignore" = { mode = "copy" }
"~/.config/gpg/gpg-agent.conf" = { mode = "symlink" }
"~/.config/gpg/gpg.conf" = { mode = "symlink" }
"~/.config/jj/config.toml" = { mode = "symlink" }
"~/.config/kube/config" = { mode = "symlink" }
"~/.config/mise" = { mode = "symlink-each"}
"~/.config/opencode" = { mode = "symlink-each" }
"~/.config/opencode/opencode.jsonc" = { mode = "symlink" }
"~/.config/opencode/tui.json" = { mode = "symlink" }
"~/.config/starship/starship.toml" = { mode = "symlink" }
"~/.config/workmux/config.yaml" = { mode = "symlink" }
"~/.config/zellij" = { mode = "symlink" }
"~/.config/zsh" = { mode = "symlink-each" }
"~/.zprezto-contrib" = { mode = "symlink" }
"~/.zshenv" = { mode = "symlink" }
