[settings]
trusted_config_paths = ["~/src/btp"]

[env]
HOLODECK_SSL_CERT_PATH = "/Users/jonno/holodeck-localhost.pem"
HOLODECK_SSL_KEY_PATH = "/Users/jonno/holodeck-localhost-key.pem"
OTEL_EXPORTER_OTLP_ENDPOINT = "http://localhost:4317"
OTEL_EXPORTER_OTLP_PROTOCOL = "grpc"

[bootstrap.packages]
"brew-cask:headlamp" = "latest"
"brew-cask:notion" = "latest"
"brew-cask:opencode-desktop" = "latest"
"brew-cask:utm" = "latest"
"brew-cask:zed" = "latest"

[tools]
"github:SigNoz/signoz-mcp-server" = "0.8.0"
cloudflared = "2026.7.2"
cosign = "3.1.2"
copilot = "1.0.73"
deno = "2.9.3"
flux2 = "2.9.2"
flux-operator = "0.55.0"
kubectl = "1.36.2"
opencode = "1.18.4"
pi = "0.80.10"
slsa-verifier = "2.7.1"
