[settings]
trusted_config_paths = ["~/src/btp"]

[env]
HOLODECK_SSL_CERT_PATH = "/Users/jonno/holodeck-localhost.pem"
HOLODECK_SSL_KEY_PATH = "/Users/jonno/holodeck-localhost-key.pem"
OTEL_EXPORTER_OTLP_ENDPOINT = "http://localhost:4317"
OTEL_EXPORTER_OTLP_PROTOCOL = "grpc"

[bootstrap.packages]
"brew-cask:headlamp" = "latest"
"brew-cask:notion" = "latest"
"brew-cask:opencode-desktop" = "latest"
"brew-cask:utm" = "latest"
"brew-cask:zed" = "latest"

[tools]
"github:SigNoz/signoz-mcp-server" = "0.14.0"
"npm:@opencode/cli" = { version = "2.0.15", allow_builds = ["@opencode/cli"], minimum_release_age = "1d" }
cosign = "3.1.3"
copilot = "v1.0.86"
deno = "2.9.7"
flux-operator = "0.60.0"
kubectl = "1.37.0"
slsa-verifier = "2.7.1"
